// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.proto;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_None_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_None_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\010protobuf\"*\n\007Message\022\017\n\007" +
      "message\030\001 \001(\t\022\016\n\006sender\030\002 \001(\t\"\006\n\004None2\267\001" +
      "\n\016messageService\0222\n\013sendMessage\022\021.protob" +
      "uf.Message\032\016.protobuf.None\"\000\022;\n\017receiveM" +
      "essages\022\021.protobuf.Message\032\021.protobuf.Me" +
      "ssage\"\0000\001\0224\n\ndisconnect\022\021.protobuf.Messa" +
      "ge\032\021.protobuf.Message\"\000B\034\n\tcom.protoB\rMe" +
      "ssageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_descriptor,
        new java.lang.String[] { "Message", "Sender", });
    internal_static_protobuf_None_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_None_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_None_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
