// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();
}
