// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.proto;

public interface NoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.None)
    com.google.protobuf.MessageOrBuilder {
}
